apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tiny-app
  template:
    metadata:
      labels:
        app: tiny-app
    spec:
      containers:
        - name: tiny-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "{{ .Values.image.tag }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 2