name: Self Hosted Runner Check

on:
  workflow_dispatch:

jobs:
  check-runner:
    runs-on: self-hosted

    steps:
      - name: Show machine
        run: |
          echo "Runner is alive"
          hostname
          uname -a

      - name: Check tools
        run: |
          docker --version
          kubectl version --client
          helm version
          minikube status