name: Minikube Check in CI Runner

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  colima:
    name: Colima
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and start Colima
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install colima qemu
          sudo setfacl -m "u:$(id -un):rw" /dev/kvm
          colima start --runtime docker --vm-type qemu
          colima status
          docker context ls
          docker --context colima info

  docker:
    name: Docker
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Docker and show status
        run: |
          sudo systemctl start docker
          systemctl is-active docker
          docker version
          docker context ls
          docker info

  minikube:
    name: Minikube
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Minikube and show status
        run: |
          sudo systemctl start docker
          minikube version
          minikube start --driver=docker
          minikube status
